name: Build

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y g++ cmake
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Package
        run: zip -j tm-linux.zip build/tm
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: tm-linux
          path: tm-linux.zip

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
      - name: Build
        run: cmake --build build --config Release
      - name: Package
        run: Compress-Archive -Path build\Release\tm.exe -DestinationPath tm-windows.zip
        shell: pwsh
      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: tm-windows
          path: tm-windows.zip
