name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y g++ cmake
      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build build --config Release
      - name: Prepare dist
        run: mkdir -p dist
      - name: Package
        run: zip -j dist/tm-linux.zip build/tm
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/tm-linux.zip


  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Configure
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
      - name: Build
        run: cmake --build build --config Release
      - name: Prepare dist
        run: mkdir -p dist
      - name: Package
        run: Compress-Archive -Path build\Release\tm.exe -DestinationPath dist/tm-windows.zip

        shell: pwsh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/tm-windows.zip

